name: Build and push Docker images

on:
  push:
    branches: [ main ]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
        
    - name: Install Prometheus
      run: |
        mkdir $HOME/prom
        cd $HOME/prom
        git clone https://github.com/prometheus/prometheus.git
        cd $HOME/prom/prometheus
        git checkout v`cat $GITHUB_WORKSPACE/PROM_VERSION`
        go install ./cmd/prometheus

    - name: Build
      run: make docker

    - name: Publish image
      uses: docker/build-push-action@v2.2.2
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        repository: aboten/prom-sidecar
        tags: main-test

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
